### ISSUE TITLE
Final test fails

### ISSUE THREAD

**Issue by DragonWarrior15** [backtrackbaba/cowin#5]
The final test whose code is listed below fails
```py
def test_min_age_limit_filter():
    cowin = CoWinAPI()
    availability = cowin.get_availability_by_district("395", min_age_limt=18)

    assert isinstance(availability, dict)
    assert isinstance(availability.get('centers'), list)
    assert len(availability.get('centers')[0].get('sessions')) == 0
```

Reason: Date is not specified, hence the results will keep changing daily depending on when the tests are run.

Solution: Pass the date parameter and accordingly correct the final assertion test (based on the readme). The below code passes the tests
```py
def test_min_age_limit_filter():
    cowin = CoWinAPI()
    availability = cowin.get_availability_by_district("395", date="03-05-2021", min_age_limt=18)

    assert isinstance(availability, dict)
    assert isinstance(availability.get('centers'), list)
    assert len(availability.get('centers')[0].get('sessions')) == 2
```

Also, in the constants file, date format needs to be corrected to be consistent with the API, `DD_MM_YYYY = "%d-%m-%y"` to `DD_MM_YYYY = "%d-%m-%Y"`.

**Comment by backtrackbaba** [comment]
Thanks, @DragonWarrior15  for the PR. It was an oversight from my end

**Comment by DragonWarrior15** [comment]
Now the oversight is from my side. This test is still failing because new slots have been added for May 7th, and the function retrieves the calendar for 7 days.
