### ISSUE TITLE
Not an issue but a general info.

### ISSUE THREAD

**Issue by kuckchuck96** [backtrackbaba/cowin#7]
Hi,

Sorry if I registered this as an issue. But I have one doubt related to deployments. I have created my custom worker script integrated cowin API and deployed it on **Heroku** and hosted it in **Europe** region (As they have US and EU as only option for worker based applications). Due to this I'm repeatedly getting 403 forbidden error codes when ever someone interacts with my bot. 

If I use this python wrapper and integrate it with my script will it benefit me with region based issues?

Thanks 🙏

**Comment by backtrackbaba** [comment]
Hey, @kuckchuck96 the region is not taken care of by the wrapper. You could use some platforms like AWS, DO, GCP which have servers in India. 

CoWin team has addressed the issue and said that the API is currently geo-fenced to India.

As a workaround, you could use any proxy that's routes traffic through India

**Comment by kuckchuck96** [comment]
Thanks @backtrackbaba 👍
